import type {
  CurriculumChapter,
  CurriculumExamSet,
  NationalCollection,
  SemesterCollection,
} from './types';

export const CURRICULUM_CHAPTERS: CurriculumChapter[] = [
  {
    id: 'dao-ham',
    subjectId: 'MATH',
    grade: 12,
    number: 1,
    title: 'Ứng dụng đạo hàm để khảo sát và vẽ đồ thị hàm số',
    shortTitle: 'Ứng dụng đạo hàm',
    lessons: [
      { id: 'tinh-don-dieu', number: 1, title: 'Tính đơn điệu của hàm số' },
      { id: 'cuc-tri', number: 2, title: 'Cực trị của hàm số' },
      { id: 'gia-tri-lon-nhat-nho-nhat', number: 3, title: 'Giá trị lớn nhất và nhỏ nhất' },
    ],
  },
  {
    id: 'mu-logarit',
    subjectId: 'MATH',
    grade: 12,
    number: 2,
    title: 'Hàm số lũy thừa, hàm số mũ và hàm số logarit',
    shortTitle: 'Hàm số lũy thừa, mũ và logarit',
    lessons: [
      { id: 'luy-thua', number: 1, title: 'Lũy thừa và hàm số lũy thừa' },
      { id: 'ham-so-mu-logarit', number: 2, title: 'Hàm số mũ và hàm số logarit' },
    ],
  },
  {
    id: 'nguyen-ham-tich-phan',
    subjectId: 'MATH',
    grade: 12,
    number: 3,
    title: 'Nguyên hàm, tích phân và ứng dụng',
    shortTitle: 'Nguyên hàm – Tích phân',
    lessons: [
      { id: 'nguyen-ham-co-ban', number: 1, title: 'Nguyên hàm cơ bản' },
      { id: 'phuong-phap-doi-bien-so', number: 2, title: 'Phương pháp đổi biến số' },
      { id: 'tich-phan-tung-phan', number: 3, title: 'Tích phân từng phần' },
    ],
  },
];

export const SEMESTER_COLLECTIONS: SemesterCollection[] = [
  {
    semester: 1,
    subjectId: 'MATH',
    grade: 12,
    title: 'Học kỳ 1',
    description:
      'Ôn tập các chương thuộc phạm vi kiểm tra học kỳ 1, từ kiến thức nền đến đề tổng hợp.',
    chapterIds: ['dao-ham', 'mu-logarit'],
  },
  {
    semester: 2,
    subjectId: 'MATH',
    grade: 12,
    title: 'Học kỳ 2',
    description:
      'Kết nối nguyên hàm, tích phân, hình học không gian và xác suất trong cấu trúc học kỳ 2.',
    chapterIds: ['nguyen-ham-tich-phan', 'hinh-hoc-khong-gian', 'xac-suat'],
  },
];

export const NATIONAL_COLLECTIONS: NationalCollection[] = [
  {
    id: 'cau-truc-de-thi',
    subjectId: 'MATH',
    grade: 12,
    title: 'Luyện cấu trúc đề thi',
    description:
      'Làm quen từng phần của cấu trúc đề, nhịp độ phân bổ thời gian và cách chuyển giữa các dạng câu hỏi.',
  },
  {
    id: 'mo-phong-ky-thi',
    subjectId: 'MATH',
    grade: 12,
    title: 'Mô phỏng kỳ thi THPT Quốc gia',
    description:
      'Thực hành trọn vẹn chương trình Toán 12 trong điều kiện thời gian và định dạng gần bài thi thật.',
  },
];

export const CURRICULUM_EXAM_SETS: CurriculumExamSet[] = [
  {
    id: 'lesson-monotonic-foundation',
    slug: 'toan-tinh-don-dieu-nhan-dien-nen',
    subjectId: 'MATH',
    grade: 12,
    scope: 'LESSON',
    tier: 'STANDARD',
    chapterId: 'dao-ham',
    lessonId: 'tinh-don-dieu',
    sequence: 1,
    title: 'Kiến thức nền',
    description: 'Đọc dấu đạo hàm và nhận biết khoảng đồng biến, nghịch biến.',
    questionCount: 18,
    durationMinutes: 25,
    difficultyLabel: 'Nền tảng',
    access: 'FREE',
    status: 'COMPLETED',
  },
  {
    id: 'lesson-monotonic-practice',
    slug: 'toan-tinh-don-dieu-cung-co',
    subjectId: 'MATH',
    grade: 12,
    scope: 'LESSON',
    tier: 'STANDARD',
    chapterId: 'dao-ham',
    lessonId: 'tinh-don-dieu',
    sequence: 2,
    title: 'Luyện thêm',
    description: 'Luyện các biểu diễn thường gặp qua bảng biến thiên và đồ thị.',
    questionCount: 20,
    durationMinutes: 30,
    difficultyLabel: 'Củng cố',
    access: 'FREE',
    status: 'IN_PROGRESS',
    resumeQuestion: 18,
  },
  {
    id: 'lesson-monotonic-application',
    slug: 'toan-tinh-don-dieu-van-dung',
    subjectId: 'MATH',
    grade: 12,
    scope: 'LESSON',
    tier: 'STANDARD',
    chapterId: 'dao-ham',
    lessonId: 'tinh-don-dieu',
    sequence: 3,
    title: 'Tổng hợp',
    description: 'Kết hợp điều kiện tham số với tính đơn điệu của hàm số.',
    questionCount: 22,
    durationMinutes: 35,
    difficultyLabel: 'Vận dụng',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'lesson-monotonic-special',
    slug: 'toan-tinh-don-dieu-tuyen-chon',
    subjectId: 'MATH',
    grade: 12,
    scope: 'LESSON',
    tier: 'SPECIAL',
    chapterId: 'dao-ham',
    lessonId: 'tinh-don-dieu',
    sequence: 4,
    title: 'Bộ đề đặc biệt',
    description: 'Những cách diễn đạt, dữ kiện và ngữ cảnh em ít gặp khi luyện tập thông thường.',
    questionCount: 18,
    durationMinutes: 35,
    difficultyLabel: 'Tình huống ít gặp',
    access: 'PLUS',
    status: 'NOT_STARTED',
  },
  {
    id: 'lesson-extrema-foundation',
    slug: 'toan-cuc-tri-nhan-dien',
    subjectId: 'MATH',
    grade: 12,
    scope: 'LESSON',
    tier: 'STANDARD',
    chapterId: 'dao-ham',
    lessonId: 'cuc-tri',
    sequence: 1,
    title: 'Nhận diện cực trị',
    description: 'Phân biệt điểm cực trị, giá trị cực trị và điều kiện đổi dấu.',
    questionCount: 18,
    durationMinutes: 25,
    difficultyLabel: 'Nền tảng',
    access: 'FREE',
    status: 'COMPLETED',
  },
  {
    id: 'lesson-extrema-graph',
    slug: 'toan-cuc-tri-do-thi',
    subjectId: 'MATH',
    grade: 12,
    scope: 'LESSON',
    tier: 'STANDARD',
    chapterId: 'dao-ham',
    lessonId: 'cuc-tri',
    sequence: 2,
    title: 'Cực trị qua đồ thị',
    description: 'Đọc và suy luận cực trị từ đồ thị hàm số và đạo hàm.',
    questionCount: 20,
    durationMinutes: 30,
    difficultyLabel: 'Củng cố',
    access: 'FREE',
    status: 'IN_PROGRESS',
    resumeQuestion: 12,
  },
  {
    id: 'lesson-extrema-parameter',
    slug: 'toan-cuc-tri-tham-so',
    subjectId: 'MATH',
    grade: 12,
    scope: 'LESSON',
    tier: 'STANDARD',
    chapterId: 'dao-ham',
    lessonId: 'cuc-tri',
    sequence: 3,
    title: 'Cực trị có tham số',
    description: 'Xác định điều kiện tham số để hàm số có số điểm cực trị cho trước.',
    questionCount: 22,
    durationMinutes: 35,
    difficultyLabel: 'Vận dụng',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'lesson-power-foundation',
    slug: 'toan-luy-thua-nen-tang',
    subjectId: 'MATH',
    grade: 12,
    scope: 'LESSON',
    tier: 'STANDARD',
    chapterId: 'mu-logarit',
    lessonId: 'luy-thua',
    sequence: 1,
    title: 'Quy tắc lũy thừa',
    description: 'Củng cố điều kiện xác định và các phép biến đổi lũy thừa.',
    questionCount: 16,
    durationMinutes: 25,
    difficultyLabel: 'Nền tảng',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'lesson-power-functions',
    slug: 'toan-luy-thua-ham-so',
    subjectId: 'MATH',
    grade: 12,
    scope: 'LESSON',
    tier: 'STANDARD',
    chapterId: 'mu-logarit',
    lessonId: 'luy-thua',
    sequence: 2,
    title: 'Hàm số lũy thừa',
    description: 'Nhận biết đồ thị và tính chất của các hàm số lũy thừa.',
    questionCount: 18,
    durationMinutes: 30,
    difficultyLabel: 'Củng cố',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'lesson-integral-substitution-foundation',
    slug: 'toan-doi-bien-so-nhan-dien',
    subjectId: 'MATH',
    grade: 12,
    scope: 'LESSON',
    tier: 'STANDARD',
    chapterId: 'nguyen-ham-tich-phan',
    lessonId: 'phuong-phap-doi-bien-so',
    sequence: 1,
    title: 'Nhận diện phép đổi biến',
    description: 'Nhận biết dấu hiệu và chọn biến phụ phù hợp trong các tích phân cơ bản.',
    questionCount: 18,
    durationMinutes: 25,
    difficultyLabel: 'Nền tảng',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'lesson-integral-substitution-guided',
    slug: 'toan-doi-bien-so-co-huong-dan',
    subjectId: 'MATH',
    grade: 12,
    scope: 'LESSON',
    tier: 'STANDARD',
    chapterId: 'nguyen-ham-tich-phan',
    lessonId: 'phuong-phap-doi-bien-so',
    sequence: 2,
    title: 'Đổi biến có hướng dẫn',
    description: 'Luyện từng bước đổi cận, đổi vi phân và rút gọn biểu thức.',
    questionCount: 20,
    durationMinutes: 30,
    difficultyLabel: 'Củng cố',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'lesson-integral-substitution-practice',
    slug: 'toan-doi-bien-so-luyen-them',
    subjectId: 'MATH',
    grade: 12,
    scope: 'LESSON',
    tier: 'STANDARD',
    chapterId: 'nguyen-ham-tich-phan',
    lessonId: 'phuong-phap-doi-bien-so',
    sequence: 3,
    title: 'Luyện thêm đổi biến số',
    description: 'Củng cố nhiều dạng đổi biến thường gặp trong đề kiểm tra và đề thi.',
    questionCount: 22,
    durationMinutes: 35,
    difficultyLabel: 'Vận dụng',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'lesson-integral-substitution-special',
    slug: 'toan-doi-bien-so-tuyen-chon',
    subjectId: 'MATH',
    grade: 12,
    scope: 'LESSON',
    tier: 'SPECIAL',
    chapterId: 'nguyen-ham-tich-phan',
    lessonId: 'phuong-phap-doi-bien-so',
    sequence: 4,
    title: 'Đổi biến trong ngữ cảnh lạ',
    description: 'Các cách đặt biến và trình bày dữ kiện ít gặp để rèn khả năng nhận diện.',
    questionCount: 20,
    durationMinutes: 40,
    difficultyLabel: 'Tình huống ít gặp',
    access: 'PLUS',
    status: 'NOT_STARTED',
  },

  {
    id: 'chapter-derivative-foundation',
    slug: 'toan-chuong-dao-ham-nen-tang',
    subjectId: 'MATH',
    grade: 12,
    scope: 'CHAPTER',
    tier: 'STANDARD',
    chapterId: 'dao-ham',
    sequence: 1,
    title: 'Kiến thức cốt lõi',
    description: 'Kiểm tra các mối liên hệ cốt lõi giữa đạo hàm, biến thiên và đồ thị.',
    questionCount: 30,
    durationMinutes: 45,
    difficultyLabel: 'Nền tảng',
    access: 'FREE',
    status: 'COMPLETED',
  },
  {
    id: 'chapter-derivative-mixed',
    slug: 'toan-chuong-dao-ham-tong-hop',
    subjectId: 'MATH',
    grade: 12,
    scope: 'CHAPTER',
    tier: 'STANDARD',
    chapterId: 'dao-ham',
    sequence: 2,
    title: 'Luyện tổng hợp',
    description: 'Luyện chuyển đổi linh hoạt giữa bảng biến thiên, đồ thị và biểu thức.',
    questionCount: 35,
    durationMinutes: 55,
    difficultyLabel: 'Củng cố',
    access: 'FREE',
    status: 'IN_PROGRESS',
    resumeQuestion: 21,
  },
  {
    id: 'chapter-derivative-application',
    slug: 'toan-chuong-dao-ham-van-dung',
    subjectId: 'MATH',
    grade: 12,
    scope: 'CHAPTER',
    tier: 'STANDARD',
    chapterId: 'dao-ham',
    sequence: 3,
    title: 'Vận dụng',
    description: 'Giải quyết các bài toán cần phối hợp nhiều nội dung trong chương.',
    questionCount: 35,
    durationMinutes: 60,
    difficultyLabel: 'Vận dụng',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'chapter-derivative-special',
    slug: 'toan-chuong-dao-ham-tuyen-chon',
    subjectId: 'MATH',
    grade: 12,
    scope: 'CHAPTER',
    tier: 'SPECIAL',
    chapterId: 'dao-ham',
    sequence: 4,
    title: 'Tình huống ít gặp',
    description:
      'Các cách trình bày dữ kiện và phối hợp khái niệm ít xuất hiện trong bài tập ở trường.',
    questionCount: 30,
    durationMinutes: 60,
    difficultyLabel: 'Tình huống ít gặp',
    access: 'PLUS',
    status: 'NOT_STARTED',
  },
  {
    id: 'chapter-log-foundation',
    slug: 'toan-chuong-mu-logarit-nen-tang',
    subjectId: 'MATH',
    grade: 12,
    scope: 'CHAPTER',
    tier: 'STANDARD',
    chapterId: 'mu-logarit',
    sequence: 1,
    title: 'Mũ và logarit',
    description: 'Rà soát quy tắc biến đổi, đồ thị và điều kiện xác định.',
    questionCount: 30,
    durationMinutes: 45,
    difficultyLabel: 'Nền tảng',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'chapter-log-equations',
    slug: 'toan-chuong-mu-logarit-phuong-trinh',
    subjectId: 'MATH',
    grade: 12,
    scope: 'CHAPTER',
    tier: 'STANDARD',
    chapterId: 'mu-logarit',
    sequence: 2,
    title: 'Phương trình mũ – logarit',
    description: 'Tổng hợp phương pháp giải và nhận diện điều kiện nghiệm.',
    questionCount: 35,
    durationMinutes: 55,
    difficultyLabel: 'Củng cố',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'chapter-log-application',
    slug: 'toan-chuong-mu-logarit-ung-dung',
    subjectId: 'MATH',
    grade: 12,
    scope: 'CHAPTER',
    tier: 'STANDARD',
    chapterId: 'mu-logarit',
    sequence: 3,
    title: 'Ứng dụng tăng trưởng',
    description: 'Mô hình hóa bài toán tăng trưởng và lãi kép bằng hàm mũ.',
    questionCount: 30,
    durationMinutes: 55,
    difficultyLabel: 'Vận dụng',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'chapter-integral-foundation',
    slug: 'toan-chuong-tich-phan-trong-tam',
    subjectId: 'MATH',
    grade: 12,
    scope: 'CHAPTER',
    tier: 'STANDARD',
    chapterId: 'nguyen-ham-tich-phan',
    sequence: 1,
    title: 'Kiến thức trọng tâm',
    description: 'Rà soát công thức nguyên hàm, các tính chất tích phân và kỹ thuật nền tảng.',
    questionCount: 30,
    durationMinutes: 45,
    difficultyLabel: 'Nền tảng',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'chapter-integral-substitution',
    slug: 'toan-chuong-tich-phan-doi-bien',
    subjectId: 'MATH',
    grade: 12,
    scope: 'CHAPTER',
    tier: 'STANDARD',
    chapterId: 'nguyen-ham-tich-phan',
    sequence: 2,
    title: 'Đổi biến và từng phần',
    description: 'Luyện chọn phương pháp phù hợp giữa đổi biến số và tích phân từng phần.',
    questionCount: 35,
    durationMinutes: 55,
    difficultyLabel: 'Củng cố',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'chapter-integral-application',
    slug: 'toan-chuong-tich-phan-ung-dung',
    subjectId: 'MATH',
    grade: 12,
    scope: 'CHAPTER',
    tier: 'STANDARD',
    chapterId: 'nguyen-ham-tich-phan',
    sequence: 3,
    title: 'Ứng dụng tích phân',
    description: 'Vận dụng tích phân vào diện tích, thể tích và các bài toán thực tế.',
    questionCount: 35,
    durationMinutes: 60,
    difficultyLabel: 'Vận dụng',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'chapter-integral-special-methods',
    slug: 'toan-chuong-tich-phan-tuyen-chon-phuong-phap',
    subjectId: 'MATH',
    grade: 12,
    scope: 'CHAPTER',
    tier: 'SPECIAL',
    chapterId: 'nguyen-ham-tich-phan',
    sequence: 4,
    title: 'Phương pháp ít gặp',
    description: 'Các tích phân cần phối hợp linh hoạt nhiều phép biến đổi.',
    questionCount: 30,
    durationMinutes: 60,
    difficultyLabel: 'Tình huống ít gặp',
    access: 'PLUS',
    status: 'NOT_STARTED',
  },
  {
    id: 'chapter-integral-special-context',
    slug: 'toan-chuong-tich-phan-tuyen-chon-ngu-canh',
    subjectId: 'MATH',
    grade: 12,
    scope: 'CHAPTER',
    tier: 'SPECIAL',
    chapterId: 'nguyen-ham-tich-phan',
    sequence: 5,
    title: 'Tích phân trong ngữ cảnh lạ',
    description: 'Dữ kiện thực tế và cách hỏi mới giúp rèn khả năng mô hình hóa.',
    questionCount: 30,
    durationMinutes: 60,
    difficultyLabel: 'Phân loại',
    access: 'PLUS',
    status: 'NOT_STARTED',
  },

  {
    id: 'semester-1-foundation',
    slug: 'toan-hoc-ky-1-nen-tang',
    subjectId: 'MATH',
    grade: 12,
    scope: 'SEMESTER',
    tier: 'STANDARD',
    semester: 1,
    sequence: 1,
    title: 'Kiến thức nền',
    description: 'Rà soát các kiến thức cần dùng xuyên suốt bài kiểm tra học kỳ 1.',
    questionCount: 40,
    durationMinutes: 60,
    difficultyLabel: 'Nền tảng',
    access: 'FREE',
    status: 'COMPLETED',
  },
  {
    id: 'semester-1-synthesis',
    slug: 'toan-hoc-ky-1-tong-hop',
    subjectId: 'MATH',
    grade: 12,
    scope: 'SEMESTER',
    tier: 'STANDARD',
    semester: 1,
    sequence: 2,
    title: 'Tổng hợp',
    description: 'Kết nối các chương trong phạm vi học kỳ bằng một đề liền mạch.',
    questionCount: 45,
    durationMinutes: 75,
    difficultyLabel: 'Củng cố',
    access: 'FREE',
    status: 'IN_PROGRESS',
    resumeQuestion: 24,
  },
  {
    id: 'semester-1-simulation',
    slug: 'toan-hoc-ky-1-mo-phong',
    subjectId: 'MATH',
    grade: 12,
    scope: 'SEMESTER',
    tier: 'STANDARD',
    semester: 1,
    sequence: 3,
    title: 'Kiểm tra thử',
    description: 'Làm bài trong cấu trúc và thời lượng của một bài kiểm tra hoàn chỉnh.',
    questionCount: 50,
    durationMinutes: 90,
    difficultyLabel: 'Tổng hợp',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'semester-1-special',
    slug: 'toan-hoc-ky-1-tuyen-chon',
    subjectId: 'MATH',
    grade: 12,
    scope: 'SEMESTER',
    tier: 'SPECIAL',
    semester: 1,
    sequence: 4,
    title: 'Tuyển chọn cách hỏi ít gặp',
    description:
      'Những cách diễn đạt, dữ kiện và ngữ cảnh khác với bài luyện tập học kỳ thông thường.',
    questionCount: 40,
    durationMinutes: 90,
    difficultyLabel: 'Tình huống ít gặp',
    access: 'PLUS',
    status: 'NOT_STARTED',
  },
  {
    id: 'semester-2-foundation',
    slug: 'toan-hoc-ky-2-nen-tang',
    subjectId: 'MATH',
    grade: 12,
    scope: 'SEMESTER',
    tier: 'STANDARD',
    semester: 2,
    sequence: 1,
    title: 'Kiến thức nền',
    description: 'Ôn lại công thức và mối liên hệ quan trọng của từng chương.',
    questionCount: 40,
    durationMinutes: 60,
    difficultyLabel: 'Nền tảng',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'semester-2-synthesis',
    slug: 'toan-hoc-ky-2-tong-hop',
    subjectId: 'MATH',
    grade: 12,
    scope: 'SEMESTER',
    tier: 'STANDARD',
    semester: 2,
    sequence: 2,
    title: 'Tổng hợp',
    description: 'Luyện cách chọn công cụ phù hợp khi dữ kiện đến từ nhiều chương.',
    questionCount: 45,
    durationMinutes: 75,
    difficultyLabel: 'Củng cố',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'semester-2-simulation',
    slug: 'toan-hoc-ky-2-mo-phong',
    subjectId: 'MATH',
    grade: 12,
    scope: 'SEMESTER',
    tier: 'STANDARD',
    semester: 2,
    sequence: 3,
    title: 'Kiểm tra thử',
    description: 'Kiểm tra khả năng phân bổ thời gian trong một đề học kỳ hoàn chỉnh.',
    questionCount: 50,
    durationMinutes: 90,
    difficultyLabel: 'Tổng hợp',
    access: 'FREE',
    status: 'NOT_STARTED',
  },

  {
    id: 'national-structure-01',
    slug: 'toan-thpt-lam-quen-cau-truc',
    subjectId: 'MATH',
    grade: 12,
    scope: 'NATIONAL',
    tier: 'STANDARD',
    nationalGroupId: 'cau-truc-de-thi',
    sequence: 1,
    publishedAt: '2026-08-07T07:00:00+07:00',
    title: 'Làm quen đề thi',
    description: 'Nhận diện các phần, dạng câu hỏi và nhịp độ của một đề Toán hoàn chỉnh.',
    questionCount: 50,
    durationMinutes: 90,
    difficultyLabel: 'Phân bố cân bằng',
    formatLabel: 'Đề thi Toán 12',
    teacherOrSource: 'Tổ biên soạn Tú Tài',
    access: 'FREE',
    status: 'COMPLETED',
  },
  {
    id: 'national-structure-02',
    slug: 'toan-thpt-chien-luoc-thoi-gian',
    subjectId: 'MATH',
    grade: 12,
    scope: 'NATIONAL',
    tier: 'STANDARD',
    nationalGroupId: 'cau-truc-de-thi',
    sequence: 2,
    publishedAt: '2026-06-18T07:00:00+07:00',
    title: 'Phân bổ thời gian',
    description: 'Thực hành thứ tự làm bài và kiểm soát thời gian theo từng phần.',
    questionCount: 50,
    durationMinutes: 90,
    difficultyLabel: 'Phân bố cân bằng',
    formatLabel: 'Đề thi Toán 12',
    teacherOrSource: 'Tổ biên soạn Tú Tài',
    access: 'FREE',
    status: 'IN_PROGRESS',
    resumeQuestion: 16,
  },
  {
    id: 'national-simulation-01',
    slug: 'toan-thpt-mo-phong-01',
    subjectId: 'MATH',
    grade: 12,
    scope: 'NATIONAL',
    tier: 'STANDARD',
    nationalGroupId: 'mo-phong-ky-thi',
    sequence: 1,
    publishedAt: '2026-08-04T07:00:00+07:00',
    title: 'Thi thử 01',
    description: 'Đề tổng hợp toàn chương trình với thời lượng và nhịp độ như kỳ thi.',
    questionCount: 50,
    durationMinutes: 90,
    difficultyLabel: 'Phân bố theo cấu trúc',
    formatLabel: 'Mô phỏng THPT Quốc gia',
    teacherOrSource: 'Tổ biên soạn Tú Tài',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'national-simulation-02',
    slug: 'toan-thpt-mo-phong-02',
    subjectId: 'MATH',
    grade: 12,
    scope: 'NATIONAL',
    tier: 'STANDARD',
    nationalGroupId: 'mo-phong-ky-thi',
    sequence: 2,
    publishedAt: '2026-05-22T07:00:00+07:00',
    title: 'Thi thử 02',
    description: 'Đề toàn diện để kiểm tra khả năng duy trì tốc độ và độ chính xác.',
    questionCount: 50,
    durationMinutes: 90,
    difficultyLabel: 'Phân bố theo cấu trúc',
    formatLabel: 'Mô phỏng THPT Quốc gia',
    teacherOrSource: 'Tổ biên soạn Tú Tài',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'national-structure-03',
    slug: 'toan-thpt-lam-quen-cau-truc-nang-cao',
    subjectId: 'MATH',
    grade: 12,
    scope: 'NATIONAL',
    tier: 'STANDARD',
    nationalGroupId: 'cau-truc-de-thi',
    sequence: 3,
    publishedAt: '2026-05-01T07:00:00+07:00',
    title: 'Làm quen cấu trúc nâng cao',
    description: 'Củng cố cách chuyển nhịp giữa các phần trong một đề Toán hoàn chỉnh.',
    questionCount: 50,
    durationMinutes: 90,
    difficultyLabel: 'Phân bố cân bằng',
    formatLabel: 'Đề thi Toán 12',
    teacherOrSource: 'Tổ biên soạn Tú Tài',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'national-simulation-03',
    slug: 'toan-thpt-bo-de-tong-hop-01',
    subjectId: 'MATH',
    grade: 12,
    scope: 'NATIONAL',
    tier: 'STANDARD',
    nationalGroupId: 'mo-phong-ky-thi',
    sequence: 3,
    publishedAt: '2026-04-18T07:00:00+07:00',
    title: 'Bộ đề tổng hợp 01',
    description: 'Rèn tốc độ và độ chính xác trên toàn bộ chương trình Toán 12.',
    questionCount: 50,
    durationMinutes: 90,
    difficultyLabel: 'Phân bố theo cấu trúc',
    formatLabel: 'Mô phỏng THPT Quốc gia',
    teacherOrSource: 'Tổ biên soạn Tú Tài',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'national-simulation-04',
    slug: 'toan-thpt-bo-de-tong-hop-02',
    subjectId: 'MATH',
    grade: 12,
    scope: 'NATIONAL',
    tier: 'STANDARD',
    nationalGroupId: 'mo-phong-ky-thi',
    sequence: 4,
    publishedAt: '2026-04-04T07:00:00+07:00',
    title: 'Bộ đề tổng hợp 02',
    description: 'Luyện sự ổn định khi xử lý liên tiếp nhiều dạng câu hỏi khác nhau.',
    questionCount: 50,
    durationMinutes: 90,
    difficultyLabel: 'Phân bố theo cấu trúc',
    formatLabel: 'Mô phỏng THPT Quốc gia',
    teacherOrSource: 'Tổ biên soạn Tú Tài',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'national-integration-application',
    slug: 'toan-thpt-ung-dung-tich-phan',
    subjectId: 'MATH',
    grade: 12,
    scope: 'NATIONAL',
    tier: 'STANDARD',
    nationalGroupId: 'cau-truc-de-thi',
    sequence: 4,
    publishedAt: '2026-03-20T07:00:00+07:00',
    title: 'Ứng dụng tích phân trong đề tổng hợp',
    description: 'Nhận diện và xử lý câu tích phân khi xuất hiện trong cấu trúc đề hoàn chỉnh.',
    questionCount: 50,
    durationMinutes: 90,
    difficultyLabel: 'Phân bố cân bằng',
    formatLabel: 'Đề thi Toán 12',
    teacherOrSource: 'Tổ biên soạn Tú Tài',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'national-simulation-05',
    slug: 'toan-thpt-bo-de-tong-hop-03',
    subjectId: 'MATH',
    grade: 12,
    scope: 'NATIONAL',
    tier: 'STANDARD',
    nationalGroupId: 'mo-phong-ky-thi',
    sequence: 5,
    publishedAt: '2026-03-02T07:00:00+07:00',
    title: 'Bộ đề tổng hợp 03',
    description: 'Tăng khả năng duy trì nhịp làm bài trong toàn bộ thời lượng 90 phút.',
    questionCount: 50,
    durationMinutes: 90,
    difficultyLabel: 'Phân bố theo cấu trúc',
    formatLabel: 'Mô phỏng THPT Quốc gia',
    teacherOrSource: 'Tổ biên soạn Tú Tài',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'national-simulation-06',
    slug: 'toan-thpt-bo-de-tong-hop-04',
    subjectId: 'MATH',
    grade: 12,
    scope: 'NATIONAL',
    tier: 'STANDARD',
    nationalGroupId: 'mo-phong-ky-thi',
    sequence: 6,
    publishedAt: '2026-02-15T07:00:00+07:00',
    title: 'Bộ đề tổng hợp 04',
    description: 'Ôn toàn diện các mạch kiến thức chính trước giai đoạn luyện đề tăng tốc.',
    questionCount: 50,
    durationMinutes: 90,
    difficultyLabel: 'Phân bố theo cấu trúc',
    formatLabel: 'Mô phỏng THPT Quốc gia',
    teacherOrSource: 'Tổ biên soạn Tú Tài',
    access: 'FREE',
    status: 'NOT_STARTED',
  },
  {
    id: 'national-simulation-special',
    slug: 'toan-thpt-tuyen-chon-cach-hoi',
    subjectId: 'MATH',
    grade: 12,
    scope: 'NATIONAL',
    tier: 'SPECIAL',
    nationalGroupId: 'mo-phong-ky-thi',
    sequence: 3,
    publishedAt: '2026-07-28T07:00:00+07:00',
    isFeatured: true,
    title: 'Tuyển chọn cách hỏi ít gặp',
    description:
      'Tuyển chọn cách diễn đạt, dữ liệu và ngữ cảnh ít gặp để rèn khả năng nhận diện kiến thức.',
    questionCount: 50,
    durationMinutes: 90,
    difficultyLabel: 'Tình huống ít gặp',
    formatLabel: 'Mô phỏng THPT Quốc gia',
    teacherOrSource: 'Tổ biên soạn Tú Tài',
    access: 'PLUS',
    status: 'NOT_STARTED',
  },
  {
    id: 'national-simulation-special-realism',
    slug: 'toan-thpt-sat-ky-thi-that',
    subjectId: 'MATH',
    grade: 12,
    scope: 'NATIONAL',
    tier: 'SPECIAL',
    nationalGroupId: 'mo-phong-ky-thi',
    sequence: 4,
    publishedAt: '2026-07-14T07:00:00+07:00',
    title: 'Đề sát kỳ thi thật',
    description: 'Mô phỏng nhịp độ, cách phân bố câu hỏi và áp lực thời gian của kỳ thi.',
    questionCount: 50,
    durationMinutes: 90,
    difficultyLabel: 'Phân bố theo cấu trúc',
    formatLabel: 'Mô phỏng THPT Quốc gia',
    teacherOrSource: 'Tổ biên soạn Tú Tài',
    access: 'PLUS',
    status: 'NOT_STARTED',
  },
  {
    id: 'national-simulation-special-rare',
    slug: 'toan-thpt-bo-de-dang-hiem',
    subjectId: 'MATH',
    grade: 12,
    scope: 'NATIONAL',
    tier: 'SPECIAL',
    nationalGroupId: 'mo-phong-ky-thi',
    sequence: 5,
    publishedAt: '2026-06-30T07:00:00+07:00',
    title: 'Bộ đề dạng hiếm',
    description: 'Tuyển chọn các cách diễn đạt và dữ kiện ít gặp nhưng vẫn đúng cấu trúc thi.',
    questionCount: 50,
    durationMinutes: 90,
    difficultyLabel: 'Tình huống ít gặp',
    formatLabel: 'Mô phỏng THPT Quốc gia',
    teacherOrSource: 'Tổ biên soạn Tú Tài',
    access: 'PLUS',
    status: 'NOT_STARTED',
  },
];
