export const PRODUCT_DEMO_CYCLE = [
  'ROADMAP_LOCKED',
  'LEARN_APPROACH',
  'LEARN_HOVER',
  'LEARN_PRESS',
  'LESSON_ENTERING',
  'LESSON_STEP_1',
  'LESSON_STEP_2',
  'LESSON_STEP_3',
  'LESSON_COMPLETE',
  'ROADMAP_LESSON_COMPLETE',
  'PRACTICE_UNLOCKING',
  'PRACTICE_READY',
  'PRACTICE_APPROACH',
  'PRACTICE_HOVER',
  'PRACTICE_PRESS',
  'PRACTICE_ACTIVE',
  'PRACTICE_Q1_APPROACH',
  'PRACTICE_Q1_HOVER',
  'PRACTICE_Q1_PRESS',
  'PRACTICE_Q1_FEEDBACK',
  'PRACTICE_Q2',
  'PRACTICE_Q2_APPROACH',
  'PRACTICE_Q2_HOVER',
  'PRACTICE_Q2_PRESS',
  'PRACTICE_Q2_FEEDBACK',
  'PRACTICE_Q3',
  'PRACTICE_Q3_APPROACH',
  'PRACTICE_Q3_HOVER',
  'PRACTICE_Q3_PRESS',
  'PRACTICE_Q3_FEEDBACK',
  'PRACTICE_COMPLETE',
  'CELEBRATING',
  'FINAL_SUMMARY',
  'RESETTING',
] as const;

export type ProductDemoScene = (typeof PRODUCT_DEMO_CYCLE)[number];

export const NEXT_PRODUCT_DEMO_SCENE = Object.fromEntries(
  PRODUCT_DEMO_CYCLE.map((scene, index) => [
    scene,
    PRODUCT_DEMO_CYCLE[(index + 1) % PRODUCT_DEMO_CYCLE.length],
  ])
) as Record<ProductDemoScene, ProductDemoScene>;
