import { featuredCompetition } from '@/data/mock-competitions';
import type { CourseEnrollment, RankingEntry, StudentCompetition } from './types';

export const STUDENT_ENROLLMENTS: CourseEnrollment[] = [
  {
    id: 'math-12-2027',
    program: 'THPT Quốc Gia 2027',
    subject: 'Toán',
    grade: 12,
    targetScore: 8.5,
    current: true,
    progress: 42,
  },
  {
    id: 'physics-12-2027',
    program: 'THPT Quốc Gia 2027',
    subject: 'Vật lý',
    grade: 12,
    current: false,
    progress: 31,
  },
  {
    id: 'chemistry-12-2027',
    program: 'THPT Quốc Gia 2027',
    subject: 'Hóa học',
    grade: 12,
    current: false,
    progress: 27,
  },
];

export const RANKING_LEADERS: RankingEntry[] = [
  { rank: 1, studentName: 'Trần Gia Huy', school: 'THPT Nguyễn Thị Minh Khai', score: 9.75 },
  { rank: 2, studentName: 'Nguyễn Minh Anh', school: 'THPT Chuyên Lê Hồng Phong', score: 9.5 },
  { rank: 3, studentName: 'Lê Hoàng Nam', school: 'THPT Gia Định', score: 9.5 },
];

export const STUDENT_HAS_PLUS = false;

export const STUDENT_ARENA_EVENTS: StudentCompetition[] = [
  {
    ...featuredCompetition,
    id: 'arena-national-math-01',
    status: 'registration_open',
    eligibility: 'plus_required',
    startAt: '2026-09-20T20:00:00+07:00',
    endAt: '2026-09-20T20:50:00+07:00',
    registrationDeadline: '2026-09-19T23:59:00+07:00',
    examSetSlug: 'toan-thpt-mo-phong-01',
    featured: true,
  },
  {
    id: 'arena-derivative-08',
    slug: 'dao-ham-08',
    title: 'Đấu trường Đạo hàm #08',
    subject: 'Toán',
    description: '6 câu trọng tâm về tính đơn điệu, cực trị và đồ thị hàm số.',
    status: 'live',
    eligibility: 'eligible',
    startAt: '2026-09-10T19:30:00+07:00',
    endAt: '2026-09-10T21:00:00+07:00',
    durationMinutes: 25,
    participantCount: 1368,
    questionCount: 6,
    plusRequired: false,
    prizePool: 1500000,
    prizes: [
      { rankFrom: 1, rankTo: 1, amount: 700000 },
      { rankFrom: 2, rankTo: 3, amount: 250000 },
      { rankFrom: 4, rankTo: 6, amount: 100000 },
    ],
    rankingRules: ['Ưu tiên điểm số, sau đó là thời gian hoàn thành.'],
    examSetSlug: 'toan-thpt-mo-phong-01',
    initiallyRegistered: true,
  },
  {
    id: 'arena-integral-09',
    slug: 'tich-phan-09',
    title: 'Đấu trường Tích phân #09',
    subject: 'Toán',
    description: 'Thử sức với đổi biến số và ứng dụng tích phân trong đề tổng hợp.',
    status: 'registration_open',
    eligibility: 'eligible',
    startAt: '2026-09-17T20:00:00+07:00',
    endAt: '2026-09-17T20:30:00+07:00',
    registrationDeadline: '2026-09-16T23:59:00+07:00',
    durationMinutes: 30,
    participantCount: 284,
    questionCount: 6,
    plusRequired: false,
    prizePool: 1000000,
    prizes: [{ rankFrom: 1, rankTo: 3, amount: 300000 }],
    rankingRules: ['Ưu tiên điểm số, sau đó là thời gian hoàn thành.'],
    examSetSlug: 'toan-thpt-ung-dung-tich-phan',
  },
  {
    id: 'arena-derivative-07',
    slug: 'dao-ham-07',
    title: 'Đấu trường Đạo hàm #07',
    subject: 'Toán',
    description: 'Sự kiện đã kết thúc; kết quả và phần thưởng đã được xác minh.',
    status: 'completed',
    eligibility: 'eligible',
    startAt: '2026-09-02T20:00:00+07:00',
    endAt: '2026-09-02T20:25:00+07:00',
    durationMinutes: 25,
    participantCount: 1284,
    questionCount: 6,
    plusRequired: false,
    prizePool: 1500000,
    prizes: [
      { rankFrom: 1, rankTo: 1, amount: 700000 },
      { rankFrom: 2, rankTo: 3, amount: 250000 },
      { rankFrom: 4, rankTo: 6, amount: 100000 },
    ],
    rankingRules: ['Ưu tiên điểm số, sau đó là thời gian hoàn thành.'],
    examSetSlug: 'toan-thpt-mo-phong-01',
  },
];
